<?php $data = $this->getConfirmPaymentOrder(); ?>
<?php if(count($data) > 0) : ?>
	<div class="box-left">
	    <div class="entry-edit">
		    <div class="entry-edit-head">
			    <h4 class="icon-head head-account"><?php echo $this->__('Confirm Payment Detail') ?></h4>
		    </div>
		    <div class="fieldset">
		    	<table cellspacing="0" class="form-list">
			    	<?php if($data['timestamp']) : ?>
				    	<tr>
			            		<td class="label"><label><?php echo $this->__('Timestamp') ?></label></td>
			            		<td class="value"><?php echo date('Y-m-d H:i:s',Mage::getModel('core/date')->timestamp($data['timestamp'])); ?></td>
				    	</tr>
			    	<?php endif; ?>
			    	<?php if($data['name']) : ?>
				    	<tr>
			            		<td class="label"><label><?php echo $this->__('Payer Name') ?></label></td>
			            		<td class="value"><?php echo $data['name']; ?></td>
				    	</tr>
			    	<?php endif; ?>
			    	<?php if($data['email']) : ?>
				    	<tr>
			            		<td class="label"><label><?php echo $this->__('Email') ?></label></td>
			            		<td class="value"><?php echo $data['email']; ?></td>
				    	</tr>
			    	<?php endif; ?>
			    	<?php if($data['bank_from']) : ?>
				    	<tr>
			            		<td class="label"><label><?php echo $this->__('Bank From') ?></label></td>
			            		<td class="value"><?php echo $data['bank_from']; ?></td>
				    	</tr>
			    	<?php endif; ?>
			    	<?php if($data['bank_to']) : ?>
				    	<tr>
			            		<td class="label"><label><?php echo $this->__('Bank To') ?></label></td>
			            		<td class="value"><?php echo $this->getToBankName($data['bank_to']); ?></td>
				    	</tr>
			    	<?php endif; ?>
			    	<?php if($data['account_number']) : ?>
				    	<tr>
			            		<td class="label"><label><?php echo $this->__('Account Number') ?></label></td>
			            		<td class="value"><?php echo $data['account_number']; ?></td>
				    	</tr>
			    	<?php endif; ?>
			    	<?php if($data['holder_name']) : ?>
				    	<tr>
			            		<td class="label"><label><?php echo $this->__('Holder Name') ?></label></td>
			            		<td class="value"><?php echo $data['holder_name']; ?></td>
				    	</tr>
			    	<?php endif; ?>
			    	<?php if($data['amount']) : ?>
				    	<tr>
			            		<td class="label"><label><?php echo $this->__('Amount') ?></label></td>
			            		<td class="value"><?php echo $data['amount']; ?></td>
				    	</tr>
			    	<?php endif; ?>
			    	<?php if($data['transfer_date']) : ?>
			    	<?php $trdate = explode(' ',$data['transfer_date']); ?>
	                <?php $trdate = strtotime($trdate[0]); ?>
	                <?php $trdate = date('d F Y',$trdate); ?>
				    	<tr>
			            		<td class="label"><label><?php echo $this->__('Transfer Date') ?></label></td>
			            		<td class="value"><?php echo $trdate; ?></td>
				    	</tr>
			    	<?php endif; ?>
	            </table>
		    </div>
	    </div>
	</div>
<div class="box-right">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-account"><?php echo $this->__('Attached File') ?></h4>
        </div>
        <div class="fieldset">
	        <?php $fileDir = Mage::getBaseDir(Mage_Core_Model_Store::URL_TYPE_MEDIA).DS.$data['filename']; ?>
	        <?php $fileUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).DS.$data['filename']; ?>
        	<?php if($data['filename'] != '' && file_exists($fileDir)) : ?>
            	<?php $filename = explode('/',$data['filename']); ?> 
                <a href="<?php echo $fileUrl; ?>" title="<?php echo $filename[1]; ?>" target="_blank"><?php echo strtoupper($filename[1]); ?></a>
                <?php else : ?>
                <p><?php echo $this->__('No File attached with this order.') ?></p>
            <?php endif; ?>
        </div>
    </div>
</div>
<?php else : ?>
<div class="box-left">
    <div class="entry-edit">
	    <div class="entry-edit-head">
		    <h4 class="icon-head head-account"><?php echo $this->__('Confirm Payment') ?></h4>
	    </div>
	    <div class="fieldset">
	    <?php echo $this->__('No records found.') ?>
	    </div>
    </div>
</div>
<?php endif; ?>